markdown: kramdown
version: 3.0.2
release_date: 2023-06-25
rabbiter_version: 2.0.3
rabbiter_release_date: 2016-08-21
rabbirack_version: 2.0.0
rabbirack_release_date: 2012-08-29
rabwii_version: 2.0.0
rabwii_release_date: 2012-08-29

defaults:
  - scope:
      path: "index.html.ja"
    values:
      layout: "ja"
      language: ja
      country: JP
  - scope:
      path: "ja"
    values:
      layout: "ja"
      language: ja
      country: JP
  - scope:
      path: ""
    values:
      layout: "en"
      language: en
      country: US
